# Generated by Django 3.2.8 on 2021-12-13 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('short', models.CharField(max_length=5)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='boards/banners/')),
                ('anonymous', models.BooleanField(default=True, help_text='Are user names hidden')),
                ('nsfw', models.BooleanField(default=False, help_text='Allow NSFW content')),
                ('secret', models.BooleanField(default=False, help_text='Is board hidden from board list')),
                ('max_threads', models.IntegerField(default=50)),
                ('max_bumps', models.IntegerField(default=150)),
                ('max_images', models.IntegerField(default=50)),
                ('allow_images', models.BooleanField(default=True)),
                ('display_images', models.BooleanField(default=True)),
                ('allow_links', models.BooleanField(default=True)),
                ('display_links', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='threads/images/')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('message', models.CharField(max_length=512)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.board')),
                ('thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.post')),
            ],
        ),
    ]
