# Generated by Django 3.2.8 on 2021-11-10 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_alter_post_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='allow_images',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='board',
            name='allow_links',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='board',
            name='anonymous',
            field=models.BooleanField(default=True, help_text='Are user names hidden'),
        ),
        migrations.AddField(
            model_name='board',
            name='display_images',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='board',
            name='display_links',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='board',
            name='max_bumps',
            field=models.IntegerField(default=150),
        ),
        migrations.AddField(
            model_name='board',
            name='max_images',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='board',
            name='secret',
            field=models.BooleanField(default=False, help_text='Is board hidden from board list'),
        ),
        migrations.AlterField(
            model_name='board',
            name='max_threads',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='board',
            name='nsfw',
            field=models.BooleanField(default=False, help_text='Allow NSFW content'),
        ),
    ]
